"""Vsector static site generator — stdlib-only, deterministic output.

Reads the repo root README.md and every doc in docs/*.md, and renders a
self-contained static site under docs/_site/ exactly as Pages would serve it.
The generator is part of the repo so the Pages job and local preview use the
same artifact; no network, no build-order imports.
"""
from __future__ import annotations

import html
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SITE = ROOT / "docs" / "_site"
README = ROOT / "README.md"

_HEAD_TPL = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title} · Vsector</title>
<style>
body{{margin:0;font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;
line-height:1.6;color:#1f2328;background:#fff}}
header{{background:#0d1117;color:#fff;padding:24px 32px}}
header a{{color:#79c0ff;text-decoration:none}}
main{{max-width:880px;margin:0 auto;padding:24px 32px}}
h1{{border-bottom:1px solid #d1d9e0;padding-bottom:.3em}}
h2,h3{{margin-top:1.6em}}
a{{color:#0969da}}
pre,code{{background:#f6f8fa;border-radius:6px;padding:2px 4px}}
pre{{overflow-x:auto;padding:12px}}
table{{border-collapse:collapse}} th,td{{border:1px solid #d1d9e0;padding:6px 12px}}
footer{{color:#57606a;font-size:13px;padding:24px 32px}}
</style>
</head>
<body>
<header><strong>Vsector</strong> — vector sharding cluster ·
<a href="./">README</a> · <a href="architecture.html">ARCHITECTURE</a> · <a href="roadmap.html">ROADMAP</a></header>
<main>
{body}
<footer>Generated by docs/gen.py · static Pages build</footer>
</main>
</body>
</html>
"""


def _code_block(m: re.Match) -> str:
    lang, body = m.group(1), m.group(2)
    code = html.escape(body.strip("\n"))
    return f"<pre><code class=\"language-{html.escape(lang or '')}\">{code}</code></pre>"


_PIPE_SEPARATOR = re.compile(r"^\s*\|?[\s:|-]+\|?\s*$")


def _cells(line: str) -> list[str]:
    text = line.strip().lstrip("|").rstrip("|")
    return [c.strip() for c in text.split("|")]


def _is_table_start(lines: list[str], i: int) -> bool:
    return "|" in lines[i] and i + 1 < len(lines) and _PIPE_SEPARATOR.match(lines[i + 1])


def _table_block_to_html(lines: list[str], i: int) -> tuple[str, int]:
    header = _cells(lines[i])
    j = i + 2
    rows: list[list[str]] = []
    while j < len(lines) and "|" in lines[j] and lines[j].strip():
        rows.append(_cells(lines[j]))
        j += 1
    out = ["<table>", "<thead><tr>" + "".join(f"<th>{html.escape(c)}</th>" for c in header) + "</tr></thead>", "<tbody>"]
    for row in rows:
        out.append("<tr>" + "".join(f"<td>{html.escape(c)}</td>" for c in row) + "</tr>")
    out.append("</tbody></table>")
    return "\n".join(out), j


def _md_to_html(text: str) -> str:
    text = re.sub(r"\n+", "\n", text).strip()
    # Protect fenced code blocks from line-by-line processing.
    blocks: list[str] = []

    def _capture(m: re.Match) -> str:
        blocks.append(_code_block(m))
        return f"\x00CODE{len(blocks) - 1}\x00"

    text = re.sub(r"```(\w*)\n(.*?)```", _capture, text, flags=re.DOTALL)
    lines = text.split("\n")
    out: list[str] = []
    i = 0
    while i < len(lines):
        line = lines[i].strip()
        if line.startswith("\x00CODE"):
            out.append(blocks[int(line[5:-1])])
        elif _is_table_start(lines, i):
            block, i = _table_block_to_html(lines, i)
            out.append(block)
            continue
        elif line.startswith("### "):
            out.append(f"<h3>{html.escape(line[4:])}</h3>")
        elif line.startswith("## "):
            out.append(f"<h2>{html.escape(line[3:])}</h2>")
        elif line.startswith("# "):
            out.append(f"<h1>{html.escape(line[2:])}</h1>")
        elif line.startswith("> "):
            out.append(f"<blockquote><p>{html.escape(line[2:])}</p></blockquote>")
        elif line.startswith("- "):
            out.append(f"<li>{html.escape(line[2:])}</li>")
        else:
            out.append(f"<p>{html.escape(line)}</p>")
        i += 1
    return "\n".join(out)


def _build() -> None:
    SITE.mkdir(parents=True, exist_ok=True)
    readme_title = "README"
    readme_html = _md_to_html(README.read_text(encoding="utf-8"))
    (SITE / "index.html").write_text(
        _HEAD_TPL.format(title=readme_title, body=readme_html), encoding="utf-8"
    )
    for md in sorted((ROOT / "docs").glob("*.md")):
        if md.name == "_site":
            continue
        name = md.stem.lower()
        html_body = _md_to_html(md.read_text(encoding="utf-8"))
        (SITE / f"{name}.html").write_text(
            _HEAD_TPL.format(title=md.stem, body=html_body), encoding="utf-8"
        )
    print(f"Built {len(list(SITE.iterdir()))} files in docs/_site")


def build() -> None:
    """Public alias: always regenerate docs/_site from source."""
    _build()


def check() -> None:
    """Verify committed docs/_site matches a fresh build (no drift).

    Used by CI so a PR that changes docs/*.md or README.md without
    regenerating the site fails loudly instead of silently publishing stale
    artifacts.
    """
    import hashlib

    def snap() -> dict[str, str]:
        return {
            p.name: hashlib.sha256(p.read_bytes()).hexdigest()
            for p in sorted(SITE.glob("*.html"))
        }

    before = snap()
    _build()
    after = snap()
    if before != after:
        missing = sorted(set(after) - set(before))
        changed = sorted(k for k in after if before.get(k) != after[k])
        print(f"docs/_site is OUT OF DATE: missing={missing} changed={changed}")
        print("run `python docs/gen.py` and commit the regenerated docs/_site")
        sys.exit(1)
    print("docs/_site is current (deterministic, no drift)")


if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] == "--check":
        check()
    else:
        _build()
